// <auto-generated />
namespace MyPOS.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nova4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nova4));
        
        string IMigrationMetadata.Id
        {
            get { return "201911181933053_nova4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
