// <auto-generated />
namespace MyPOS.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _1011 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1011));
        
        string IMigrationMetadata.Id
        {
            get { return "201910040257064_1.0.11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
