// <auto-generated />
namespace MyPOS.Repositorio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0-preview3-19553-01")]
    public sealed partial class nova7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nova7));
        
        string IMigrationMetadata.Id
        {
            get { return "201911191519314_nova7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
