//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_UF_AUTORIZADORA
    {
        public int ID { get; set; }
        public string UF { get; set; }
        public int COD_UF { get; set; }
        public string URL_CONSULTA { get; set; }
        public int AMBIENTE { get; set; }
        public string URL_RECEPCAO { get; set; }
        public string URL_RECEPCAO_EVENTO { get; set; }
        public string URL_STATUS_SERVICO { get; set; }
        public string URL_QRCODE { get; set; }
        public string VERSAO_LAYOUT { get; set; }
        public System.DateTime DATA_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public int VERSAO { get; set; }
    }
}
