//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_VERSAO_GERAL
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public string SCRIPT_SQLSERVER { get; set; }
        public string SCRIPT_MYSQL { get; set; }
        public string SCRIPT_ORACLE { get; set; }
        public string DLL_SERVICO { get; set; }
    }
}
