//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_CONTROLE_SERIE
    {
        public int ID { get; set; }
        public int CODIGO_TIPO { get; set; }
        public int SERIE_INICIAL { get; set; }
        public int SERIE_FINAL { get; set; }
        public int SERIE_ATUAL { get; set; }
        public int SUB_SERIE_INICIAL { get; set; }
        public int SUB_SERIE_FINAL { get; set; }
        public int SUB_SERIE_ATUAL { get; set; }
        public int CODIGO_EMITENTE { get; set; }
        public bool COMPLETA { get; set; }
    
        public virtual BPE_CONFIGURACAO_EMITENTE BPE_CONFIGURACAO_EMITENTE { get; set; }
        public virtual BPE_TIPO_APLICACAO BPE_TIPO_APLICACAO { get; set; }
    }
}
