//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_SCHEMA
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public byte[] REGRAS { get; set; }
        public System.DateTime DATA_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public int VERSAO { get; set; }
    }
}
