//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_CONFIG_SERVICO
    {
        public int ID { get; set; }
        public int CODIGO_CLIENTE { get; set; }
        public string VESAO_CONFIG_BANCO { get; set; }
        public System.DateTime DATA { get; set; }
        public Nullable<System.DateTime> DATA_ONLINE { get; set; }
    }
}
