//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_USUARIOS
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string SENHA { get; set; }
        public Nullable<int> PERFIL { get; set; }
        public Nullable<System.DateTime> DATA_CADASTRO { get; set; }
        public bool ATIVO { get; set; }
        public Nullable<int> CODIGO_EMPRESA { get; set; }
        public bool POSSUI_RODOCHECKIN { get; set; }
    }
}
