//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_SERIE_BILHETE
    {
        public int ID { get; set; }
        public int CODIGO_TIPO { get; set; }
        public int SERIE { get; set; }
        public int SUB_SERIE { get; set; }
        public int BILHETE { get; set; }
        public int CODIGO_EMITENTE { get; set; }
        public int CODIGO_CLIENTE { get; set; }
        public string IMEI { get; set; }
    
        public virtual BPE_CLIENTE BPE_CLIENTE { get; set; }
        public virtual BPE_CONFIGURACAO_EMITENTE BPE_CONFIGURACAO_EMITENTE { get; set; }
        public virtual BPE_TIPO_APLICACAO BPE_TIPO_APLICACAO { get; set; }
    }
}
