//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPE_CLIENTE()
        {
            this.BPE_LOG_CLIENTE = new HashSet<BPE_LOG_CLIENTE>();
            this.BPE_SERIE_BILHETE = new HashSet<BPE_SERIE_BILHETE>();
        }
    
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public int TIPO_CLIENTE { get; set; }
        public string CNPJ { get; set; }
        public string NOME_FISCAL { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public int CODIGO_MUNICIPIO { get; set; }
        public int CEP { get; set; }
        public string LOGRADOURO { get; set; }
        public string BAIRRO { get; set; }
        public string MUNICIPIO { get; set; }
        public string UF { get; set; }
        public int NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_ONLINE { get; set; }
        public Nullable<int> QTD_DLL { get; set; }
        public string VERSAO_SCRIPT { get; set; }
        public string VERSAO_DLL { get; set; }
        public Nullable<int> CODIGO_EMPRESA { get; set; }
        public Nullable<int> CODIGO_RODOVIARIA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_LOG_CLIENTE> BPE_LOG_CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_SERIE_BILHETE> BPE_SERIE_BILHETE { get; set; }
    }
}
