//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_CERTIFICADO
    {
        public int ID { get; set; }
        public int CODIGO_CONFIGURACAO_EMITENTE { get; set; }
        public string CERTIFICADO { get; set; }
        public string SENHA { get; set; }
        public System.DateTime DATA_INICIAL { get; set; }
        public System.DateTime DATA_FINAL { get; set; }
        public int VERSAO { get; set; }
    }
}
