//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_TIPO_APLICACAO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPE_TIPO_APLICACAO()
        {
            this.BPE_CONTROLE_SERIE = new HashSet<BPE_CONTROLE_SERIE>();
            this.BPE_SERIE_BILHETE = new HashSet<BPE_SERIE_BILHETE>();
        }
    
        public int ID { get; set; }
        public string DESCRICAO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_CONTROLE_SERIE> BPE_CONTROLE_SERIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_SERIE_BILHETE> BPE_SERIE_BILHETE { get; set; }
    }
}
