//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_CONFIGURACAO_EMITENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BPE_CONFIGURACAO_EMITENTE()
        {
            this.BPE_BPES = new HashSet<BPE_BPES>();
            this.BPE_CONTROLE_SERIE = new HashSet<BPE_CONTROLE_SERIE>();
            this.BPE_SERIE_BILHETE = new HashSet<BPE_SERIE_BILHETE>();
        }
    
        public int ID { get; set; }
        public int CODIGO_EMPRESA { get; set; }
        public string CNPJ { get; set; }
        public int CNAE_FISCAL { get; set; }
        public int CODIGO_REGIME_TRIBUTARIO { get; set; }
        public string INSCRICAO_ESTADUAL { get; set; }
        public string INSCRICAO_ESTADUAL_SUB_TRIBUTARIO { get; set; }
        public string INSCRICAO_MUNICIPAL { get; set; }
        public string NOME_FISCAL { get; set; }
        public string RAZAO_SOCIAL { get; set; }
        public string TERMO_AUTORIZACAO_SERV_REGULAR { get; set; }
        public int CEP { get; set; }
        public int CODIGO_MUNICIPIO { get; set; }
        public string LOGRADOURO { get; set; }
        public string BAIRRO { get; set; }
        public string MUNICIPIO { get; set; }
        public string NUMERO { get; set; }
        public string COMPLEMENTO { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public string UF { get; set; }
        public string INFORMACAO_ADICIONAL { get; set; }
        public bool ATIVO { get; set; }
        public Nullable<System.DateTime> DATA_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
        public Nullable<int> CODIGO_IBGE { get; set; }
        public Nullable<bool> BPE_CONTRATADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_BPES> BPE_BPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_CONTROLE_SERIE> BPE_CONTROLE_SERIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BPE_SERIE_BILHETE> BPE_SERIE_BILHETE { get; set; }
    }
}
