//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_UF_TRIBUTACAO
    {
        public int ID { get; set; }
        public string UF { get; set; }
        public decimal ALIQUOTA_INTERESTADUAL { get; set; }
        public decimal ALIQUOTA_INTERMUNICIPAL { get; set; }
        public string CLASSIFICACAO_TRIBUTARIA { get; set; }
        public System.DateTime DATA_INCLUSAO { get; set; }
        public Nullable<System.DateTime> DATA_ALTERACAO { get; set; }
    }
}
