//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class BPE_LOG_CLIENTE
    {
        public int ID { get; set; }
        public System.DateTime DATA { get; set; }
        public int CODIGO_CLIENTE { get; set; }
        public string ERRO { get; set; }
        public int TIPO { get; set; }
        public string MENSAGEM { get; set; }
        public int ENVIADO { get; set; }
    
        public virtual BPE_CLIENTE BPE_CLIENTE { get; set; }
    }
}
