//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPE_CENTRALEntities : DbContext
    {
        public BPE_CENTRALEntities()
            : base("name=BPE_CENTRALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BPE_BPES> BPE_BPES { get; set; }
        public virtual DbSet<BPE_CERTIFICADO> BPE_CERTIFICADO { get; set; }
        public virtual DbSet<BPE_CLIENTE> BPE_CLIENTE { get; set; }
        public virtual DbSet<BPE_CLIENTE_EMITENTE> BPE_CLIENTE_EMITENTE { get; set; }
        public virtual DbSet<BPE_CONFIG_SERVICO> BPE_CONFIG_SERVICO { get; set; }
        public virtual DbSet<BPE_CONFIGURACAO_EMITENTE> BPE_CONFIGURACAO_EMITENTE { get; set; }
        public virtual DbSet<BPE_CONTROLE_SERIE> BPE_CONTROLE_SERIE { get; set; }
        public virtual DbSet<BPE_LOG_CLIENTE> BPE_LOG_CLIENTE { get; set; }
        public virtual DbSet<BPE_PROCESSADO> BPE_PROCESSADO { get; set; }
        public virtual DbSet<BPE_SCHEMA> BPE_SCHEMA { get; set; }
        public virtual DbSet<BPE_SERIE_BILHETE> BPE_SERIE_BILHETE { get; set; }
        public virtual DbSet<BPE_TIPO_APLICACAO> BPE_TIPO_APLICACAO { get; set; }
        public virtual DbSet<BPE_UF_AUTORIZADORA> BPE_UF_AUTORIZADORA { get; set; }
        public virtual DbSet<BPE_UF_TRIBUTACAO> BPE_UF_TRIBUTACAO { get; set; }
        public virtual DbSet<BPE_USUARIOS> BPE_USUARIOS { get; set; }
        public virtual DbSet<BPE_VERSAO_DLL_SERVICO> BPE_VERSAO_DLL_SERVICO { get; set; }
        public virtual DbSet<BPE_VERSAO_GERAL> BPE_VERSAO_GERAL { get; set; }
        public virtual DbSet<BPE_VERSAO_SCRIPT> BPE_VERSAO_SCRIPT { get; set; }
    }
}
