//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_embarque_passagem_bpe
    {
        public int codigo { get; set; }
        public System.DateTime data_leitura { get; set; }
        public bool embarcado { get; set; }
        public string viagem_id { get; set; }
        public string chave { get; set; }
        public string prefixo { get; set; }
        public string origem_ibge_venda { get; set; }
        public string destino_ibge_venda { get; set; }
        public int modalidade { get; set; }
        public int poltrona { get; set; }
        public System.DateTime data_viagem { get; set; }
        public bool validada { get; set; }
        public bool verificada { get; set; }
        public int cod_usuario { get; set; }
        public string device { get; set; }
    }
}
