//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_user_status
    {
        public int id { get; set; }
        public int cod_user { get; set; }
        public int ativo { get; set; }
        public Nullable<System.DateTime> dt_insercao { get; set; }
        public Nullable<System.DateTime> dt_alteracao { get; set; }
    }
}
