//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_info_device
    {
        public string imei { get; set; }
        public string versao_OS { get; set; }
        public string versao_app { get; set; }
        public string marca_device { get; set; }
        public string numero_modelo { get; set; }
        public string operadora { get; set; }
        public Nullable<int> altura_tela { get; set; }
        public Nullable<int> largura_tela { get; set; }
        public Nullable<int> densidade_tela { get; set; }
        public int ativo { get; set; }
        public Nullable<System.DateTime> dt_insercao { get; set; }
        public Nullable<System.DateTime> dt_alteracao { get; set; }
    }
}
