//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_log_rodochechin
    {
        public int id { get; set; }
        public string rotina { get; set; }
        public string mensagem { get; set; }
        public Nullable<int> empresa_codigo { get; set; }
        public Nullable<int> usuario_codigo { get; set; }
        public System.DateTime data_hora { get; set; }
        public string imei { get; set; }
    }
}
