//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_log_desembarque_passagem
    {
        public int Id { get; set; }
        public int usuario_id { get; set; }
        public string motivo { get; set; }
        public System.DateTime data_desembarque { get; set; }
        public string chave_bpe { get; set; }
    }
}
