//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class rdc_empresa_config
    {
        public int id_empresa_config { get; set; }
        public bool confirma_login { get; set; }
        public int tempo_confirma_login { get; set; }
        public int tempo_inicio_viagem { get; set; }
    }
}
