//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpeCentral.Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RDC_DEV_Entities : DbContext
    {
        public RDC_DEV_Entities()
            : base("name=RDC_DEV_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<rdc_embarque_passagem_bpe> rdc_embarque_passagem_bpe { get; set; }
        public virtual DbSet<rdc_info_device> rdc_info_device { get; set; }
        public virtual DbSet<rdc_log_desembarque_passagem> rdc_log_desembarque_passagem { get; set; }
        public virtual DbSet<rdc_log_rodochechin> rdc_log_rodochechin { get; set; }
        public virtual DbSet<rdc_user_status> rdc_user_status { get; set; }
        public virtual DbSet<rdc_version_info> rdc_version_info { get; set; }
        public virtual DbSet<rdc_empresa_config> rdc_empresa_config { get; set; }
    }
}
